title: A guide to League of Legends
author: MisterKrisobg
email: MyEmail@ThisIs100%Real.com
description: > # this means to ignore newlines until "baseurl:"
  A guide on the basics of League of Legends and how to improve.

# social links
twitter_username: Nah
github_username: MisterKrisobg

show_excerpts: true # set to false to remove excerpts on the homepage
theme: mininma
